### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [schadokar/array-shifter#1]
If you want I can write a TypeScript types declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by schadokar** [comment]
Hi, thanks for your interest. I have added the MIT License in the project. Please go ahead create what you required. Please fork the repo, create a new branch, make the changes and create a pull request. Please also add instructions on how TS and JS people can use it. I have no experience in TS. Thanks for contributing.

**Comment by geopic** [comment]
I'll get started then @schadokar. As for instructions on how to use it, you don't deliberately 'use' declaration files -- they are there so that when a developer writing in TypeScript uses a library that is written in JavaScript (like this one), they are informed of what type of value is required in function arguments, what type of value is returned from functions, etc. TypeScript is an additional layer on top of JavaScript which adds static typing, just like Golang has.
